### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by IzzySoft** [jinweijie/notify-me#1]
I could not find any details on this when browsing your repo. Could you please clarify what license your code falls under? Maybe MIT, like the Bark Server itself? Thanks in advance!

**Comment by IzzySoft** [comment]
PS: Please remember to always [increase `versionCode`](https://github.com/jinweijie/notify-me/blob/master/app/build.gradle.kts#L14) when making a release. Android uses that to tell versions apart; if it wasn't increased it will be considered "already installed" and thus never offered for update on the device.

**Comment by jinweijie** [comment]
> PS: Please remember to always [increase `versionCode`](https://github.com/jinweijie/notify-me/blob/master/app/build.gradle.kts#L14) when making a release. Android uses that to tell versions apart; if it wasn't increased it will be considered "already installed" and thus never offered for update on the device.

Thanks for the hint, I will do for next release.

**Comment by jinweijie** [comment]
> I could not find any details on this when browsing your repo. Could you please clarify what license your code falls under? Maybe MIT, like the Bark Server itself? Thanks in advance!

I am a free software (not OSS) believer, so I use [WTFPL](http://www.wtfpl.net/) if you ask. 😆

**Comment by IzzySoft** [comment]
WTF!!! Haha, that's totally fine of course. And to shock you (or not): even approved as F/LOSS license by the FSF :rofl:

But yeah, to confirm the other way to read your sentence: "open" (to look at) does not suffice, it must meet the [4 essential freedoms of free software](https://en.wikipedia.org/wiki/Free_and_open-source_software#Four_essential_freedoms_of_Free_Software) :smiley:

That said, I'm just adding your app to the [IzzyOnDroid repo](https://apt.izzysoft.de/fdroid) now, it will [show up here](https://apt.izzysoft.de/packages/com.jinweijie.notifyme) with the next sync around 6 pm UTC. And congrats, it succeeded as [Reproducible Build](https://reproducible-builds.org/) and hence will carry the green shield confirming that! Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme if you wish.

----

PS: Some scanner reports you might be interested in. [According to VT](https://www.virustotal.com/gui/file/1b8282f0c8ba9cc1545abd15f8591ecc1e52990471dcf00e59908259c20257dd/detection/f-1b8282f0c8ba9cc1545abd15f8591ecc1e52990471dcf00e59908259c20257dd-1728691469), Avast and Trustlook do not seem to like your app. I'd count this as false positives (as none of the other 64 scanners there complains, and at least Avast has such from time to time) – but just in case someone asks, so you are prepared.

The local scanners here reported:

```
! repo/com.jinweijie.notifyme_1.apk declares flag(s): usesCleartextTraffic
! repo/com.jinweijie.notifyme_1.apk declares sensitive permission(s): android.permission.RECEIVE_SMS android.permission.READ_SMS android.permission.READ_PHONE_STATE android.permission.PROCESS_OUTGOING_CALLS android.permission.READ_CALL_LOG
! repo/com.jinweijie.notifyme_1.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

Most of those are clear: clearText to connect to self-hosted instances in the local network, the permissions all meet the purpose of the app and thus went to its "green list":

```yaml
    android.permission.RECEIVE_SMS: needed to detect incoming SMS and process them
    android.permission.READ_SMS: needed to get the content of SMS and forward them
    android.permission.PROCESS_OUTGOING_CALLS: needed to log outgoing calls
    android.permission.READ_PHONE_STATE: used to detect incoming calls
    android.permission.READ_CALL_LOG: needed to obtain details on incoming calls to forward them
```

(hope that's all correct? If not just let me know and I correct it. Like, to detect incoming calls it does not necessarily need `READ_PHONE_STATE`but one could simply register to the `onAudioFocusChanged` broadcast, so this might be used for more than that. The idea here is transparency: if I wonder about some sensible permission but get a proper explanation, I know I needn't be concerned).

Another point is `DEPENDENCY_INFO_BLOCK`, which can easily be avoided with a minor addition to your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

![image](https://github.com/user-attachments/assets/2aaf082b-01fb-4867-8e81-cfb79038fc69)

I'll leave the issue open as reminder for that blob, be welcome to simply close it when you consider things done. Thanks for your help, and welcome aboard IzzyOnDroid :smiley:

**Comment by IzzySoft** [comment]
PS: Mind to add the license to the Readme – so the next one does not need to ask? :wink:

**Comment by jinweijie** [comment]
> PS: Mind to add the license to the Readme – so the next one does not need to ask? 😉

Hi @IzzySoft , good day, I've added the license part in README. 

Would you be ok if I close this issue?

Thanks. :)

**Comment by IzzySoft** [comment]
> Would you be ok if I close this issue?

Have you addressed the other issue, too – `DEPENDENCY_INFO_BLOCK`? I cannot find a corresponding section in the `build.gradle`.

**Comment by jinweijie** [comment]
> > Would you be ok if I close this issue?
> 
> Have you addressed the other issue, too – `DEPENDENCY_INFO_BLOCK`? I cannot find a corresponding section in the `build.gradle`.

Just updated, thanks.

**Comment by IzzySoft** [comment]
Great, thanks then!
