### ISSUE TITLE
请问未来会支持以表单方式post信息给webhook接口吗

### ISSUE THREAD

**Issue by jhcn** [jinweijie/notify-me#5]
RT

**Comment by jinweijie** [comment]
@jhcn 你好，目前是json post, 表单暂时没有计划，请问具体大概是什么场景？谢谢

**Comment by jhcn** [comment]
> @jhcn 你好，目前是json post, 表单暂时没有计划，请问具体大概是什么场景？谢谢

由于历史原因，本人写的接收端接收application/x-www-form-urlencoded数据，且应用在多处，不便于重构。再则没能力在您现有开源代码基础上定制需要功能。只能提issues了，如无支持计划多有打扰 /抱拳

**Comment by jinweijie** [comment]
@jhcn 明白，这并不困难，等我有空的时候会加一个选项把json转成form提交，谢谢。

**Comment by jinweijie** [comment]
@jhcn 已经增加form提交选项，1.4.0版本。
